server:
  port: 8088 #修改项目启动的端口为8088
#配置数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xnfzdb?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: Hdh4568520
      initial-size: 5
      max-active: 20
  devtools:
    restart:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #兼容swagger
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl